{{- if not .Values.database.existingSecret -}}
{{- if not .Values.database.password -}}
{{- fail "database.password must be set when database.existingSecret is empty" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dam-release-collector.fullname" . }}
  labels:
    {{- include "dam-release-collector.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.userKey }}: {{ .Values.database.user | quote }}
  {{ .Values.database.passwordKey }}: {{ .Values.database.password | quote }}
{{- end -}}
